// dummy data for testing
export const projects = [
    {
        id: '617e9b2c6e2d647f28b062p0',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Canopy with Spandrel Installation',
        location: 'Redwood Subdivision, Consolacion, Cebu',
        bg_project_img: '/src/assets/images/project1.jpeg',
        project_imgs: [
            '/src/assets/images/project1.jpeg',
            '/src/assets/images/project1.1.jpeg',
        ],
        date_completed: '05/04/2022',
        description: ["Spandrels, also known as brackets or gallows, are intended to add additional support to the construction while also improving the overall visual appeal. For structural support, all of our cantilever door canopies require spandrels, and the size of the brackets will depend on the overall size of the canopy."
        ],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p1',
        task_id: '617e9b2c6e2d647f28b062ts',
        title: 'Custom Cabinets',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project2.jpeg',
        project_imgs: [
            '/src/assets/images/project2.jpeg',
            '/src/assets/images/project2.1.jpeg',
            '/src/assets/images/project2.2.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ["Sturdy and Durable. Custom cabinets that are specially designed with your tastes and preferences in mind and then meticulously handcrafted in a shop to be later delivered and installed inside your home. Custom cabinets are quality-built with real wood and can be as modern or traditional as desired.If you would like a Customs Cabinets please don’t hesitate to get in touch."
        ],
        service: 'Cabinets',
    },
    {
        id: '617e9b2c6e2d647f28b062p2',
        task_id: '617e9b2c6e2d647f28b062t2',
        title: 'Bar Counter Installation',
        location: 'Summerville Subdivision,Ibabao Cordova',
        bg_project_img: '/src/assets/images/project3.jpeg',
        project_imgs: [
            '/src/assets/images/project3.jpeg'
        ],
        date_completed: '08/09/2023',
        description: ["Bar Counters are often found just outside the kitchen and are used to serve food and drinks sitting at the opposite side of it or to waiters to be distributed onwards to diners sitting in the restaurant seating area.If you would like a Bar Counter Installation please don’t hesitate to get in touch."],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p3',
        task_id: '617e9b2c6e2d647f28b062t2',
        title: 'Ceiling Spandrel Repair and Installation ',
        location: 'Summerville Subdivision, Ibabao Cordova',
        bg_project_img: '/src/assets/images/project4.jpeg',
        project_imgs: [
            '/src/assets/images/project4.jpeg',
            '/src/assets/images/project4.1.jpeg',
            '/src/assets/images/project4.2.jpeg',
            '/src/assets/images/project4.3.jpeg',
            '/src/assets/images/project4.4.jpeg'
        ],
        date_completed: '08/09/2023',
        description: ["In addition to their aesthetic function, spandrel panels may also serve practical purposes. They can provide insulation, soundproofing, and fire resistance properties, contributing to the overall performance of the building envelope. It is indeed a practical choice.If you would like a Ceiling Spandrel Repair and Installation please don’t hesitate to get in touch."],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p4',
        task_id: '617e9b2c6e2d647f28b062t1',
        title: 'Custom Bedrooms',
        location: 'Summerville Subdivision, Ibabao Cordova',
        bg_project_img: '/src/assets/images/project5.jpeg',
        project_imgs: [
            '/src/assets/images/project5.jpeg',
            '/src/assets/images/project5.1.jpeg',
            '/src/assets/images/project5.2.jpeg'
        ],
        date_completed: '08/09/2023',
        description: ["Sturdy and Durable. Custom bedrooms that are specially designed with your tastes and preferences in mind and then meticulously handcrafted in a shop to be later delivered and installed inside your home. Custom bedrooms are quality-built with real wood and can be as modern or traditional as desired.If you would like a Customs bedrooms please don’t hesitate to get in touch."],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p5',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Roofing Reinstalled',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project6.jpeg',
        project_imgs: [
            '/src/assets/images/project6.jpeg',
            '/src/assets/images/6jbuilders-bg.jpg',
        ],
        date_completed: '08/09/2023',
        description: ["Your roof is your home's first line of defense against wind, rain, hail, and heat. It's regularly exposed to weather hazards and other harsh elements that contribute to its natural deterioration. However, your roof won't be able to weather storms for years to come if it isn't properly installed. If you would like a Roofing Reinstallation please don't hesitate to get in touch."],
        service: 'Home Repair Services',
    },
    {
        id: '617e9b2c6e2d647f28b062p5',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Full bathroom tiles and Safety Translucent Glass installation',
        location: 'Summerville Subdivision, Ibabao Cordova',
        bg_project_img: '/src/assets/images/project11.jpeg',
        project_imgs: [
            '/src/assets/images/project11.jpeg',
            '/src/assets/images/project11.1.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ["Cutting and fitting tiles around obstacles and openings using hand and power cutting tools. Preparing, measuring and marking surfaces to be covered. Mixing, applying and spreading cement, glue or other adhesives using hand tools. Aligning and straightening tiles using levels and squares.If you would like a Full Bathroom Tiles Installation please don’t hesitate to get in touch."],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p6',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Custom Arrangement for TV Installation',
        location: 'Summerville Subdivision, Ibabao Cordova',
        bg_project_img: '/src/assets/images/project8.jpeg',
        project_imgs: [
            '/src/assets/images/project8.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ["Ideally, placing your television at an angle that prevents sunlight from glaring at it and away from busy areas are the best places to put it. For the optimal viewing angle, you may wish to install your TV higher than eye level, depending on how you have things set up.If you would like a Custom Arrangement for TV Installation please don’t hesitate to get in touch."],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p7',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Full House Renovations',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project9.jpeg',
        project_imgs: [
            '/src/assets/images/project9.jpeg',
            '/src/assets/images/project9.1.jpeg',
            '/src/assets/images/project9.2.jpeg',
            '/src/assets/images/project9.3.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ["Restoring your home to its former glory? Making cosmetic improvements, replacing existing fittings or furnishings, and updating flooring, doors, or windows all fall under the rubric of renovating.The project will include interior and exterior renovation and rehabilitation to upgrade infrastructures.If you would like a Full House Renovation please don’t hesitate to get in touch."],
        service: 'Home Renovations',
    },
    {
        id: '617e9b2c6e2d647f28b062p8',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Ceiling Light Installation',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project10.jpeg',
        project_imgs: [
            '/src/assets/images/project10.jpeg'
        ],
        date_completed: '08/09/2023',
        description: ['Seeking for solutions for a gloomy room? When it comes to small spaces or rooms with low ceilings, ceiling lights are an excellent option. You may get good, practical general lighting with a big lighting surface by using a ceiling lamp. Wall-mounted ceiling lights can produce a sophisticated aesthetic impression. There are many different types of ceiling lighting fixtures available, such as semi-flush ceiling lights, track lights, recessed lights, and flush mount fixtures.If you would like a custom Ceiling Light Installation please don’t hesitate to get in touch.'
        ],
        service: 'Home Repair Services',
    },
    {
        id: '617e9b2c6e2d647f28b062p9',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Customized Bathrooms',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project12.jpeg',
        project_imgs: [
            '/src/assets/images/project12.jpeg',
            '/src/assets/images/project12.1.jpeg',
            '/src/assets/images/project12.2.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ['Bathrooms should be beautiful. Contemplating your style and the materials you choose to personalize your space needs to be well thought out and will make it interesting. Consider a unique piece of furniture for the vanity or a custom-built cabinet.  Select different tiles for the shower that coordinate with the rest of the bathroom, along with the vanity top options, hardware style, and flooring to give the space its own unique flare.If you would like a Customs Bathroom please don’t hesitate to get in touch.'],
        service: 'Home Repair Services',
    },
    {
        id: '617e9b2c6e2d647f28b062p10',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Gate Installation',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project13.jpeg',
        project_imgs: [
            '/src/assets/images/project13.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ['Imagine efficiently controlling who enters your property. One of the best ways to quickly and instantly have more control over your property’s security is with the installation of a driveway gate. With this feature, you gain many benefits for your property such as, security,property value, safety,convenience,curb appeal and privacy.If you would like a custom Gate Installation please don’t hesitate to get in touch.'],
        service: 'Home Repair Services',
    },
    {
        id: '617e9b2c6e2d647f28b062p11',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Steel Decking Installation',
        location: 'Mandaue, Cebu City, Cebu',
        bg_project_img: '/src/assets/images/project14.jpeg',
        project_imgs: [
            '/src/assets/images/project14.jpeg',
        ],
        date_completed: '08/09/2023',
        description: ['Steel decking is resistant to weather, moisture, deterioration from pests, and twisting and warping over time. can be utilized as a structural element in roofs and floors. It serves to hold insulating membranes in place. Since their designs can be changed to suit the needs of the client, they are a great option for flooring in many construction sites.If you would like a Steel Decking installation please don’t hesitate to get in touch.'
        ],
        service: 'Home Repair Services',
    },
    {
        id: '617e9b2c6e2d647f28b062p12',
        task_id: '617e9b2c6e2d647f28b062t4',
        title: 'Full House Renovation',
        location: 'Redwood Subdivision, Consolacion Cebu',
        bg_project_img: '/src/assets/images/project15.jpg',
        project_imgs: [
            'src/assets/images/project15.jpg',
            'src/assets/images/project15.1.jpg',
            'src/assets/images/project15.2.jpg',
            'src/assets/images/project15.3.jpg',
            'src/assets/images/project15.4.jpg'
        ],
        date_completed: '08/09/2023',
        description: ['Restoring your home to its former glory? Making cosmetic improvements, replacing existing fittings or furnishings, and updating flooring, doors, or windows all fall under the rubric of renovating.The project will include interior and exterior renovation and rehabilitation to upgrade infrastructures.If you would like a Full House Renovation please don’t hesitate to get in touch.',
        ],
        service: 'Home Renovations',
    },
];