// dummy data for testing
export const projects = [
    {
        id: 1,
        title: 'Remodeling the House',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project1.jpeg',
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
            'Tortor consequat id porta nibh venenatis cras sed felis eget. Libero enim sed faucibus turpis. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Est ultricies integer quis auctor elit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. At quis risus sed vulputate odio ut enim blandit. Turpis tincidunt id aliquet risus feugiat.'],
        service: 'Home Renovations',
    },
    {
        id: 2,
        title: 'Custom Cabinets',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project2.jpeg',
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
            'Tortor consequat id porta nibh venenatis cras sed felis eget. Libero enim sed faucibus turpis. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Est ultricies integer quis auctor elit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. At quis risus sed vulputate odio ut enim blandit. Turpis tincidunt id aliquet risus feugiat.'],
        service: 'Cabinets',
    },
    {
        id: 3,
        title: 'Repairing Room',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project3.jpeg',
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
            'Tortor consequat id porta nibh venenatis cras sed felis eget. Libero enim sed faucibus turpis. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Est ultricies integer quis auctor elit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. At quis risus sed vulputate odio ut enim blandit. Turpis tincidunt id aliquet risus feugiat.'],
        service: 'Home Renovations',
    },
    {
        id: 4,
        title: 'Repairing a Comfort Room',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project4.jpeg',
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
            'Tortor consequat id porta nibh venenatis cras sed felis eget. Libero enim sed faucibus turpis. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Est ultricies integer quis auctor elit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. At quis risus sed vulputate odio ut enim blandit. Turpis tincidunt id aliquet risus feugiat.'],
        service: 'Plumbing',
    },
    {
        id: 5,
        title: 'Custom Bedrooms',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project5.jpeg',
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
            'Tortor consequat id porta nibh venenatis cras sed felis eget. Libero enim sed faucibus turpis. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Est ultricies integer quis auctor elit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. At quis risus sed vulputate odio ut enim blandit. Turpis tincidunt id aliquet risus feugiat.'],
        service: 'Home Renovations',
    },
    {
        id: 6,
        title: 'Adding a Roof',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project6.jpeg',
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
            'Tortor consequat id porta nibh venenatis cras sed felis eget. Libero enim sed faucibus turpis. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Est ultricies integer quis auctor elit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. At quis risus sed vulputate odio ut enim blandit. Turpis tincidunt id aliquet risus feugiat.'],
        service: 'Roofting',
    },
];
