// dummy data for testing
export const projects = [
    {
        id: 1,
        title: 'Canopy with Spandrel Ceiling',
        location: 'Redwood Subdivision, Consolacion, Cebu',
        image: '/src/assets/images/project1.jpeg',
        projectImages: [
            '/src/assets/images/project1.jpeg',
            '/src/assets/images/project1.1.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '05/04/2022',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 2,
        title: 'Custom Cabinets',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project2.jpeg',
        projectImages: [
            '/src/assets/images/project2.jpeg',
            '/src/assets/images/project2.1.jpeg',
            '/src/assets/images/project2.2.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Cabinets',
    },
    {
        id: 3,
        title: 'Bar Counter Installation',
        location: 'Summerville Subdivision,Ibabao Cordova',
        image: '/src/assets/images/project3.jpeg',
        projectImages: [
            '/src/assets/images/project3.jpeg'
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 4,
        title: 'Kesami Repair and Spandrel Installation',
        location: 'Summerville Subdivision, Ibabao Cordova',
        image: '/src/assets/images/project4.jpeg',
        projectImages: [
            '/src/assets/images/project4.jpeg',
            '/src/assets/images/project4.1.jpeg',
            '/src/assets/images/project4.2.jpeg',
            '/src/assets/images/project4.3.jpeg',
            '/src/assets/images/project4.4.jpeg'
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 5,
        title: 'Custom Bedrooms',
        location: ' Summerville Subdivision, Ibabao Cordova',
        image: '/src/assets/images/project5.jpeg',
        projectImages: [
            '/src/assets/images/project5.jpeg',
            '/src/assets/images/project5.1.jpeg',
            '/src/assets/images/project5.2.jpeg'
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 6,
        title: 'Roofing Reinstalled',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project6.jpeg',
        projectImages: [
            '/src/assets/images/project6.jpeg',
            '/src/assets/images/6jbuilders-bg.jpg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Repair Services',
    },
    {
        id: 7,
        title: 'Full bathroom tiles and Safety Translucent Glass installation',
        location: 'Summerville Subdivision, Ibabao Cordova',
        image: '/src/assets/images/project11.jpeg',
        projectImages: [
            '/src/assets/images/project11.jpeg',
            '/src/assets/images/project11.1.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 8,
        title: 'Custom Arrangement for TV Installation',
        location: 'Summerville Subdivision, Ibabao Cordova',
        image: '/src/assets/images/project8.jpeg',
        projectImages: [
            '/src/assets/images/project8.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 9,
        title: 'Full House Renovations',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project9.jpeg',
        projectImages: [
            '/src/assets/images/project9.jpeg',
            '/src/assets/images/project9.1.jpeg',
            '/src/assets/images/project9.2.jpeg',
            '/src/assets/images/project9.3.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
    {
        id: 10,
        title: 'Ceiling Light Installation',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project10.jpeg',
        projectImages: [
            '/src/assets/images/project10.jpeg'
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Repair Services',
    },
    {
        id: 11,
        title: 'Custom CR Installation',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project12.jpeg',
        projectImages: [
            '/src/assets/images/project12.jpeg',
            '/src/assets/images/project12.1.jpeg',
            '/src/assets/images/project12.2.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Repair Services',
    },
    {
        id: 12,
        title: 'Gate Installation',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project13.jpeg',
        projectImages: [
            '/src/assets/images/project13.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Repair Services',
    },
    {
        id: 13,
        title: 'Steel Decking Installation',
        location: 'Mandaue, Cebu City, Cebu',
        image: '/src/assets/images/project14.jpeg',
        projectImages: [
            '/src/assets/images/project14.jpeg',
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Repair Services',
    },
    {
        id: 14,
        title: 'Full House Renovation',
        location: 'Redwood Subdivision, Consolacion Cebu',
        image: '/src/assets/images/project15.jpg',
        projectImages: [
            'src/assets/images/project15.jpg',
            'src/assets/images/project15.1.jpg',
            'src/assets/images/project15.2.jpg',
            'src/assets/images/project15.3.jpg',
            'src/assets/images/project15.4.jpg'
        ],
        rating: 4.5,
        reviews: 413,
        date: '08/09/2023',
        description: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.',
            'Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Magna etiam tempor orci eu lobortis elementum nibh tellus. Ac placerat vestibulum lectus mauris ultrices. Duis at consectetur lorem donec. Nisl purus in mollis nunc sed. Amet mauris commodo quis imperdiet massa.',
        ],
        service: 'Home Renovations',
    },
];
